# Generated by Django 4.0.5 on 2022-07-13 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AppCoder.persona')),
                ('domicilio', models.CharField(max_length=50)),
                ('altura', models.IntegerField()),
                ('telefono', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('AppCoder.persona',),
        ),
        migrations.CreateModel(
            name='Info_Adicional',
            fields=[
                ('contacto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AppCoder.contacto')),
                ('profesion', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(max_length=20)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
            bases=('AppCoder.contacto', 'AppCoder.persona'),
        ),
    ]
